### ISSUE TITLE
inviteCandidate

### ISSUE THREAD

**Issue by vvaalleerraa** [zpix1/about-me#1]
const essentialTypeScript = require('Знание TypeScript');
const basicJava = require('понимание Java');
const basicPython = require('понимание Python');

function inviteCandidate() {
    console.log("Ищу кандидата в команду ИИ-разработки всего очень интересного");
    
    if (essentialTypeScript && basicJava && basicPython) {
        console.log("Найден кандидат!");
        console.log("Он умеет:");
        console.log("- TypeScript: " + essentialTypeScript);
        console.log("- Java: " + basicJava);
        console.log("- Python: " + basicPython);
    } else {
        console.log("К сожалению, кандидат не найден. Попробуйте еще раз.");
    }
}

inviteCandidate();

**Comment by zpix1** [comment]
Добрый день! 
По таким вопросам лучше писать на почту, [zpix-dev@list.ru](mailto:zpix-dev@list.ru).
